language: node_js

node_js:
  - 6.10.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e86922b2b181e3d4c1c0
    on_success: always
    on_failure: always
    on_start: always

  slack:
    secure: cDuc+rC8JeCMWpZs5EHbUAYJSafWO/m65DsQWbuuWflpK/ROja19lwbCe5PZn+aG7L0QVeQATZEwj4pkrvfow9rK2GqJNh25nR595v6p2ZVNe/379VhqKWjGdqMRlxwfEz45MFR1bgF2eGHiHq9r1fQ26fca3EO3ZMKs6UC6c26SUBBO8Sgq2uTVe6quLsTrllPtljuCDAIJFrANs1eqVmFLNrBYjzsNgjWgLsjsmy58OoXdmzMh6pCAIuQVlCIt7pm146zm4ZdrAMt/tPeQeppicpGVXc2qmrHxt2qqPjdzexCGBSYgJXLTuHrQD9MX8YQhCtAJ4wCitP67sEqVrs1rldN1r6eXIaOn2xuVyJH1RJyrwwRfEFhysBFeZs5jo+WF0NZba7Kys6DOocJ2s+O9SB2DLkQQc5yqJKvib+BRr2ULAS7PB5S/FAb0g0+to5GopPjCNOxVkbyhTTHI2HPhd1QDMfOdsosoiV3sqXY5Z0QjZtufMgT9tk9Bdonh6dIZBZrFvsq3KNjplRyhgkGtiDYN15VI4XInNbZpEwQjaYSfEZsXKn7jRuhsrmRV/BCljMTqXsQ2ofWKAmEAGBy730WMG4QfvCVHvtbwFxWonPR18kFj8fNcqBIl8optDQgqVS5WaMgu7iBrZ6dGVzjPnWzrCjMtiK3Io5F5dxA=

install:
  - npm install -g ng
  - npm install

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
