codecov:
  notify:
    require_ci_to_pass: true

comment:
  behavior: default
  layout: header, diff
  require_changes: false

coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  notify:
    gitter:
      default:
        url: https://webhooks.gitter.im/e/025504f93bf2fb637e81
        branches:
          - master
        threshold: null
    slack:
      default:
        url: https://hooks.slack.com/services/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
        branches:
          - master
        threshold: null

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
enable_partials: false
